'use strict';

/**
 * Portfolio Service
 *
 * Provides access to a user's latest mortgage portfolio data.
 * Used by the enhanced analysis controller to supply portfolio context
 * to the report generation engine for comparison against bank offers.
 *
 * Data Sources (in priority order):
 *   1. `portfolios` Firestore collection – saved portfolio scenarios
 *      generated by the wizard (recommended portfolio is preferred).
 *   2. `wizardInputs` Firestore collection – raw wizard submission data
 *      used as a fallback when no saved portfolio exists.
 *   3. null – returned gracefully when neither source has data.
 *
 * Portfolio shape returned:
 * {
 *   id:              string   (Firestore document ID)
 *   userId:          string
 *   type:            string   (scenario type, e.g. 'market_standard')
 *   name:            string   (English name)
 *   nameHe:          string   (Hebrew name)
 *   termYears:       number
 *   tracks:          Array<{ type, percentage, rate, rateDisplay, amount,
 *                            monthlyPayment, totalCost, totalInterest }>
 *   monthlyRepayment: number
 *   totalCost:       number
 *   totalInterest:   number
 *   averageRate:     number   (weighted average rate across tracks)
 *   recommended:     boolean
 *   source:          'portfolios' | 'wizardInputs'  (internal metadata)
 * }
 *
 * @module portfolioService
 */

const { getDb } = require('../config/db');
const COLLECTIONS = require('../config/collections');
const logger = require('../utils/logger');

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Compute a weighted average interest rate across portfolio tracks.
 *
 * Each track's rate is weighted by its percentage allocation.
 * Returns null if no valid tracks are provided.
 *
 * @param {Array<object>} tracks - Portfolio tracks
 * @returns {number|null} Weighted average rate, or null
 */
function computeAverageRate(tracks) {
  if (!Array.isArray(tracks) || tracks.length === 0) return null;

  let weightedSum = 0;
  let totalWeight = 0;

  for (const track of tracks) {
    const rate = typeof track.rate === 'number' ? track.rate : null;
    const pct = typeof track.percentage === 'number' ? track.percentage : 0;

    if (rate !== null && pct > 0) {
      weightedSum += rate * pct;
      totalWeight += pct;
    }
  }

  if (totalWeight === 0) return null;

  return Math.round((weightedSum / totalWeight) * 10000) / 10000;
}

/**
 * Select the best portfolio from a list of saved portfolios.
 *
 * Preference order:
 *   1. Portfolio marked as `recommended: true`
 *   2. Portfolio with the highest `fitnessScore`
 *   3. First portfolio in the list
 *
 * @param {Array<object>} portfolios - List of portfolio documents
 * @returns {object|null} Best portfolio, or null if list is empty
 */
function selectBestPortfolio(portfolios) {
  if (!portfolios || portfolios.length === 0) return null;

  // Prefer the recommended portfolio
  const recommended = portfolios.find((p) => p.recommended === true);
  if (recommended) return recommended;

  // Fall back to highest fitness score
  const sorted = [...portfolios].sort(
    (a, b) => (b.fitnessScore || 0) - (a.fitnessScore || 0)
  );
  return sorted[0];
}

// ── Primary Source: portfolios collection ─────────────────────────────────────

/**
 * Fetch the user's latest saved portfolio from the `portfolios` collection.
 *
 * Queries for all portfolios belonging to the user, ordered by `updatedAt`
 * descending (falls back to `createdAt` if `updatedAt` is absent).
 * Returns the best portfolio from the most recent wizard session.
 *
 * @param {string} userId - Firebase Auth UID
 * @returns {Promise<object|null>} Portfolio document, or null if none found
 */
async function fetchFromPortfoliosCollection(userId) {
  const db = getDb();

  try {
    // Query portfolios ordered by updatedAt descending to get the latest first
    const snapshot = await db
      .collection(COLLECTIONS.PORTFOLIOS)
      .where('userId', '==', userId)
      .orderBy('updatedAt', 'desc')
      .limit(10)
      .get();

    if (snapshot.empty) {
      logger.debug('portfolioService.fetchFromPortfoliosCollection: no portfolios found', { userId });
      return null;
    }

    // Collect all portfolios from the snapshot
    const portfolios = [];
    snapshot.forEach((doc) => {
      portfolios.push({ id: doc.id, ...doc.data() });
    });

    logger.debug(
      `portfolioService.fetchFromPortfoliosCollection: found ${portfolios.length} portfolios`,
      { userId }
    );

    // Select the best portfolio (recommended > highest score > first)
    const best = selectBestPortfolio(portfolios);
    if (!best) return null;

    // Enrich with computed average rate
    const averageRate = computeAverageRate(best.tracks);

    return {
      ...best,
      averageRate,
      source: 'portfolios',
    };
  } catch (err) {
    // Handle Firestore index errors gracefully – fall back to createdAt ordering
    if (err.code === 9 || (err.message && err.message.includes('index'))) {
      logger.warn(
        'portfolioService.fetchFromPortfoliosCollection: index not ready, retrying without orderBy',
        { userId, error: err.message }
      );
      return fetchFromPortfoliosCollectionNoOrder(userId);
    }

    logger.error(
      `portfolioService.fetchFromPortfoliosCollection: error for user ${userId}: ${err.message}`
    );
    throw err;
  }
}

/**
 * Fallback query for portfolios collection without ordering.
 * Used when the composite index is not yet available.
 *
 * @param {string} userId - Firebase Auth UID
 * @returns {Promise<object|null>} Portfolio document, or null
 */
async function fetchFromPortfoliosCollectionNoOrder(userId) {
  const db = getDb();

  try {
    const snapshot = await db
      .collection(COLLECTIONS.PORTFOLIOS)
      .where('userId', '==', userId)
      .limit(20)
      .get();

    if (snapshot.empty) return null;

    const portfolios = [];
    snapshot.forEach((doc) => {
      portfolios.push({ id: doc.id, ...doc.data() });
    });

    // Sort in-memory by updatedAt or createdAt descending
    portfolios.sort((a, b) => {
      const dateA = a.updatedAt || a.createdAt || '';
      const dateB = b.updatedAt || b.createdAt || '';
      return dateB.localeCompare(dateA);
    });

    const best = selectBestPortfolio(portfolios);
    if (!best) return null;

    return {
      ...best,
      averageRate: computeAverageRate(best.tracks),
      source: 'portfolios',
    };
  } catch (err) {
    logger.error(
      `portfolioService.fetchFromPortfoliosCollectionNoOrder: error for user ${userId}: ${err.message}`
    );
    return null;
  }
}

// ── Fallback Source: wizardInputs collection ──────────────────────────────────

/**
 * Derive a lightweight portfolio context from the user's wizard inputs.
 *
 * When no saved portfolio exists, the wizard inputs provide enough context
 * (loan amount, term, stability preference) for the report service to
 * generate a meaningful comparison. This returns a minimal portfolio-like
 * object derived from the wizard submission.
 *
 * @param {string} userId - Firebase Auth UID
 * @returns {Promise<object|null>} Derived portfolio context, or null
 */
async function fetchFromWizardInputs(userId) {
  const db = getDb();

  try {
    // wizardInputs uses userId as the document ID (see wizardInputService.js)
    const doc = await db
      .collection(COLLECTIONS.WIZARD_INPUTS)
      .doc(userId)
      .get();

    if (!doc.exists) {
      logger.debug('portfolioService.fetchFromWizardInputs: no wizard inputs found', { userId });
      return null;
    }

    const data = doc.data();
    const inputs = data.inputs || data;

    // Validate that we have the minimum required fields
    if (!inputs.loanAmount || !inputs.propertyPrice) {
      logger.debug(
        'portfolioService.fetchFromWizardInputs: wizard inputs missing required fields',
        { userId }
      );
      return null;
    }

    logger.debug('portfolioService.fetchFromWizardInputs: derived portfolio from wizard inputs', {
      userId,
    });

    // Build a minimal portfolio-like object from wizard inputs
    // This gives the report service enough context for comparison
    return {
      id: `wizard-${userId}`,
      userId,
      type: 'wizard_derived',
      name: 'Wizard Portfolio',
      nameHe: 'תיק מהאשף',
      termYears: 30, // Default term
      tracks: [], // No specific tracks from wizard alone
      monthlyRepayment: null,
      totalCost: null,
      totalInterest: null,
      averageRate: null,
      recommended: false,
      // Preserve wizard inputs for report context
      loanAmount: inputs.loanAmount,
      propertyPrice: inputs.propertyPrice,
      monthlyIncome: inputs.monthlyIncome || null,
      stabilityPreference: inputs.stabilityPreference || null,
      targetRepayment: inputs.targetRepayment || null,
      source: 'wizardInputs',
    };
  } catch (err) {
    logger.error(
      `portfolioService.fetchFromWizardInputs: error for user ${userId}: ${err.message}`
    );
    // Non-critical – return null so the report can still be generated
    return null;
  }
}

// ── Main Entry Point ──────────────────────────────────────────────────────────

/**
 * Get the user's latest portfolio for use in enhanced report generation.
 *
 * Implements a two-source fallback strategy:
 *   1. Query `portfolios` collection for saved wizard-generated portfolios.
 *      Returns the recommended (or highest-scoring) portfolio.
 *   2. If no saved portfolio exists, derive context from `wizardInputs`.
 *   3. Return null if neither source has data (report service handles null).
 *
 * This function never throws – errors are caught and logged, returning null
 * so the enhanced report can still be generated without portfolio context.
 *
 * @param {string} userId - Firebase Auth UID of the authenticated user
 * @returns {Promise<object|null>} User's latest portfolio, or null
 *
 * @example
 * const portfolio = await portfolioService.getUserPortfolio(userId);
 * // portfolio may be null – reportService handles this gracefully
 * const report = await reportService.generateEnhancedReport(
 *   offerId, userId, offer, portfolio
 * );
 */
async function getUserPortfolio(userId) {
  if (!userId) {
    logger.warn('portfolioService.getUserPortfolio: called with empty userId');
    return null;
  }

  logger.info('portfolioService.getUserPortfolio: fetching portfolio', { userId });

  try {
    // Source 1: saved portfolios collection
    const savedPortfolio = await fetchFromPortfoliosCollection(userId);
    if (savedPortfolio) {
      logger.info('portfolioService.getUserPortfolio: returning saved portfolio', {
        userId,
        portfolioId: savedPortfolio.id,
        type: savedPortfolio.type,
        source: savedPortfolio.source,
      });
      return savedPortfolio;
    }

    // Source 2: wizard inputs fallback
    logger.info(
      'portfolioService.getUserPortfolio: no saved portfolio, falling back to wizard inputs',
      { userId }
    );
    const wizardPortfolio = await fetchFromWizardInputs(userId);
    if (wizardPortfolio) {
      logger.info('portfolioService.getUserPortfolio: returning wizard-derived portfolio', {
        userId,
        source: wizardPortfolio.source,
      });
      return wizardPortfolio;
    }

    // No portfolio data available
    logger.info('portfolioService.getUserPortfolio: no portfolio data found for user', { userId });
    return null;
  } catch (err) {
    // Catch-all: log and return null so the report flow is not blocked
    logger.error(
      `portfolioService.getUserPortfolio: unexpected error for user ${userId}: ${err.message}`
    );
    return null;
  }
}

// ── Exports ───────────────────────────────────────────────────────────────────

module.exports = {
  // Main entry point
  getUserPortfolio,

  // Internal helpers (exported for testing)
  computeAverageRate,
  selectBestPortfolio,
  fetchFromPortfoliosCollection,
  fetchFromWizardInputs,
};
